version: "2.1"
services:
  babybuddy:
    image: crutonjohn/babybuddy-local:test
    container_name: babybuddy
    environment:
      - TZ=UTC
      - SECRET_KEY=Lgr49twDV2d7
      - BABYBUDDY__PORT=9090
    ports:
      - 9090:9090
    restart: unless-stopped
  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/var/www/babybuddy/data/media
    restart: unless-stopped
